# Generated by Django 2.0.7 on 2018-11-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181111_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onehourelectricity',
            old_name='date_time',
            new_name='date_time_db',
        ),
    ]
